filter:
    paths:
        - src/*
tools:
    php_analyzer:
        config:
            parameter_reference_check:
                enabled:              true
            checkstyle:
                enabled:              true
                naming:
                    enabled:              true
                    interface_name:       ^[A-Z][a-zA-Z0-9]*Interface$
                    exception_name:       ^[A-Z][a-zA-Z0-9]*Exception$
                    isser_method_name:    ^(?:is|has|should|may|supports)
